config/routes.rb
Rails.application.routes.draw do

  resources :pages, only: :show
  resources :contacts, only: [:new, :create]
  resources :articles, only: [:index, :show]
  resources :services, only: [:index, :show]
  resources :testimonials, only: [:index]
  resources :frequently_asked_questions, path: "frequently-asked-questions", only: [:index]

  root to: "application#index"
  mount Optimadmin::Engine => "/admin"
end
Optimadmin::Engine.routes.draw do

  resources :pathway_sections, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
    resources :pathway_jigsaw_pieces, except: [:show] do
      collection do
        post 'order'
      end
      member do
        get 'toggle'
      end
    end
    resources :pathway_rows, except: [:show] do
      collection do
        post 'order'
      end
      member do
        get 'toggle'
      end
    end
  end
  resources :locations, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :contact_details, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :frequently_asked_questions, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :testimonials, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :banners, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :services, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :pages, except: :show do
    collection do
      post 'order'
    end
    member do
      get 'edit_images'
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :articles, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base

  has_many :service_testimonials, dependent: :destroy
  has_many :services, through: :service_testimonials

  scope :displayed, -> { where(display: true) }
  scope :service_home, -> { where(service_home: true) }
  scope :for_service, ->(service) { joins(:service_testimonials).where(service_testimonials: { service_id: service.id }) if service.present? }
  scope :service_filter, ->(service_id) { joins(:service_testimonials).where(service_testimonials: { service_id: service_id }) if service_id.present? }

  validates :author, :content, presence: true
end

app/controllers/optimadmin/articles_controller.rb
module Optimadmin
  class ArticlesController < Optimadmin::ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    edit_images_for Article, [[:image, { index: ['fill', 223, 223], show: ['fill', 215, 315], homepage: ['fill', '100, 100'] }]]

    def index
      @articles = Optimadmin::BaseCollectionPresenter.new(collection: Article.where('title ILIKE ?', "#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::ArticlePresenter)
    end

    def show
    end

    def new
      @article = Article.new
    end

    def edit
    end

    def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to articles_url, notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    def update
      if @article.update(article_params)
        redirect_to articles_url, notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @article.destroy
      redirect_to articles_url, notice: 'Article was successfully destroyed.'
    end

  private


    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :summary, :content, :image, :image_cache, :remote_image_url, :date, :display, :suggested_url)
    end
  end
end

app/controllers/optimadmin/banners_controller.rb
module Optimadmin
  class BannersController < Optimadmin::ApplicationController
    before_action :set_banner, only: [:show, :edit, :update, :destroy]

    edit_images_for Banner, [[:image, { homepage: ['fit', 560, 276] }]]

    def index
      @banners = Optimadmin::BaseCollectionPresenter.new(collection: Banner.order(position: :asc), view_template: view_context, presenter: Optimadmin::BannerPresenter)
    end

    def show
    end

    def new
      @banner = Banner.new
    end

    def edit
    end

    def create
      @banner = Banner.new(banner_params)
      if @banner.save
        redirect_to banners_url, notice: 'Banner was successfully created.'
      else
        render :new
      end
    end

    def update
      if @banner.update(banner_params)
        redirect_to banners_url, notice: 'Banner was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @banner.destroy
      redirect_to banners_url, notice: 'Banner was successfully destroyed.'
    end

  private


    def set_banner
      @banner = Banner.find(params[:id])
    end

    def banner_params
      params.require(:banner).permit(:name, :image, :image_cache, :remote_image_url, :content, :position, :display, :link)
    end
  end
end

app/controllers/optimadmin/contact_details_controller.rb
module Optimadmin
  class ContactDetailsController < Optimadmin::ApplicationController
    before_action :set_contact_detail, only: [:show, :edit, :update, :destroy]

    def index
      @contact_details = Optimadmin::BaseCollectionPresenter.new(collection: ContactDetail.service_filter(params[:service_id]).where('name ILIKE ?', "#{params[:search]}%").order(:service_id).page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::ContactDetailPresenter)
    end

    def show
    end

    def new
      @contact_detail = ContactDetail.new
    end

    def edit
    end

    def create
      @contact_detail = ContactDetail.new(contact_detail_params)
      if @contact_detail.save
        redirect_to contact_details_url, notice: 'Contact detail was successfully created.'
      else
        render :new
      end
    end

    def update
      if @contact_detail.update(contact_detail_params)
        redirect_to contact_details_url, notice: 'Contact detail was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @contact_detail.destroy
      redirect_to contact_details_url, notice: 'Contact detail was successfully destroyed.'
    end

  private


    def set_contact_detail
      @contact_detail = ContactDetail.find(params[:id])
    end

    def contact_detail_params
      params.require(:contact_detail).permit(:service_id, :name, :address, :postcode, :phone_number, :email, :opening_hours)
    end
  end
end

app/controllers/optimadmin/frequently_asked_questions_controller.rb
module Optimadmin
  class FrequentlyAskedQuestionsController < Optimadmin::ApplicationController
    before_action :set_frequently_asked_question, only: [:show, :edit, :update, :destroy]

    def index
      @frequently_asked_questions = Optimadmin::BaseCollectionPresenter.new(collection: FrequentlyAskedQuestion.service_filter(params[:service_id]).where('question ILIKE ?', "#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::FrequentlyAskedQuestionPresenter)
    end

    def show
    end

    def new
      @frequently_asked_question = FrequentlyAskedQuestion.new
    end

    def edit
    end

    def create
      @frequently_asked_question = FrequentlyAskedQuestion.new(frequently_asked_question_params)
      if @frequently_asked_question.save
        redirect_to frequently_asked_questions_url, notice: 'Frequently asked question was successfully created.'
      else
        render :new
      end
    end

    def update
      if @frequently_asked_question.update(frequently_asked_question_params)
        redirect_to frequently_asked_questions_url, notice: 'Frequently asked question was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @frequently_asked_question.destroy
      redirect_to frequently_asked_questions_url, notice: 'Frequently asked question was successfully destroyed.'
    end

  private


    def set_frequently_asked_question
      @frequently_asked_question = FrequentlyAskedQuestion.find(params[:id])
    end

    def frequently_asked_question_params
      params.require(:frequently_asked_question).permit(:question, :answer, :display, :service_home, service_ids: [])
    end
  end
end

app/controllers/optimadmin/pages_controller.rb
module Optimadmin
  class PagesController < Optimadmin::ApplicationController
    before_action :set_page, only: [:show, :edit, :update, :destroy]

    edit_images_for Page, [[:image, { show: ['fit', 756, 200] }]]

    def index
      @pages = Optimadmin::BaseCollectionPresenter.new(collection: Page.service_filter(params[:service_id]).where('title ILIKE ?', "#{params[:search]}%").order(:service_id).page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::PagePresenter)
    end

    def show
    end

    def new
      @page = Page.new
    end

    def edit
    end

    def create
      @page = Page.new(page_params)
      if @page.save
        redirect_to pages_url, notice: 'Page was successfully created.'
      else
        render :new
      end
    end

    def update
      if @page.update(page_params)
        redirect_to pages_url, notice: 'Page was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @page.destroy
      redirect_to pages_url, notice: 'Page was successfully destroyed.'
    end

  private


    def set_page
      @page = Page.friendly.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:title, :suggested_url, :image, :image_cache, :remove_image, :remote_image_url,
                                   :display, :content, :style, :layout, :service_id)
    end
  end
end

app/controllers/optimadmin/pathway_jigsaw_pieces_controller.rb
module Optimadmin
  class PathwayJigsawPiecesController < Optimadmin::ApplicationController

    before_action :set_pathway_section
    before_action :set_pathway_jigsaw_piece, only: [:show, :edit, :update, :destroy]

    def index
      @pathway_jigsaw_pieces = Optimadmin::BaseCollectionPresenter.new(collection: @pathway_section.pathway_jigsaw_pieces.ordered,
                                       view_template: view_context, presenter: Optimadmin::PathwayJigsawPiecePresenter)
    end

    def show
    end

    def new
      @pathway_jigsaw_piece = @pathway_section.pathway_jigsaw_pieces.new
    end

    def edit
    end

    def create
      @pathway_jigsaw_piece = @pathway_section.pathway_jigsaw_pieces.new(pathway_jigsaw_piece_params)
      if @pathway_jigsaw_piece.save
        redirect_to pathway_section_pathway_jigsaw_pieces_url(@pathway_section), notice: 'Pathway jigsaw piece was successfully created.'
      else
        render :new
      end
    end

    def update
      if @pathway_jigsaw_piece.update(pathway_jigsaw_piece_params)
        redirect_to pathway_section_pathway_jigsaw_pieces_url(@pathway_section), notice: 'Pathway jigsaw piece was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @pathway_jigsaw_piece.destroy
      redirect_to pathway_section_pathway_jigsaw_pieces_url(@pathway_section), notice: 'Pathway jigsaw piece was successfully destroyed.'
    end

  private

    def set_pathway_section
      @pathway_section = PathwaySection.find(params[:pathway_section_id])
    end

    def set_pathway_jigsaw_piece
      @pathway_jigsaw_piece = @pathway_section.pathway_jigsaw_pieces.find(params[:id])
    end

    def pathway_jigsaw_piece_params
      params.require(:pathway_jigsaw_piece).permit(:pathway_section_id, :name, :position, :colour, :display)
    end
  end
end

app/controllers/optimadmin/pathway_rows_controller.rb
module Optimadmin
  class PathwayRowsController < Optimadmin::ApplicationController

    before_action :set_pathway_section
    before_action :set_pathway_row, only: [:show, :edit, :update, :destroy]

    def index
      @pathway_rows = Optimadmin::BaseCollectionPresenter.new(collection: @pathway_section.pathway_rows.ordered,
                                                view_template: view_context, presenter: Optimadmin::PathwayRowPresenter)
    end

    def show
    end

    def new
      @pathway_row = @pathway_section.pathway_rows.new
    end

    def edit
    end

    def create
      @pathway_row = @pathway_section.pathway_rows.new(pathway_row_params)
      if @pathway_row.save
        redirect_to pathway_section_pathway_rows_url(@pathway_section), notice: 'Pathway row was successfully created.'
      else
        render :new
      end
    end

    def update
      if @pathway_row.update(pathway_row_params)
        redirect_to pathway_section_pathway_rows_url(@pathway_section), notice: 'Pathway row was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @pathway_row.destroy
      redirect_to pathway_section_pathway_rows_url(@pathway_section), notice: 'Pathway row was successfully destroyed.'
    end

  private

    def set_pathway_section
      @pathway_section = PathwaySection.find(params[:pathway_section_id])
    end

    def set_pathway_row
      @pathway_row = @pathway_section.pathway_rows.find(params[:id])
    end

    def pathway_row_params
      params.require(:pathway_row).permit(:pathway_section_id, :name, :content, :colour, :display)
    end
  end
end

app/controllers/optimadmin/pathway_sections_controller.rb
module Optimadmin
  class PathwaySectionsController < Optimadmin::ApplicationController
    before_action :set_pathway_section, only: [:show, :edit, :update, :destroy]

    def index
      @pathway_sections = Optimadmin::BaseCollectionPresenter.new(collection: PathwaySection.ordered,
                                  view_template: view_context, presenter: Optimadmin::PathwaySectionPresenter)
    end

    def show
    end

    def new
      @pathway_section = PathwaySection.new
    end

    def edit
    end

    def create
      @pathway_section = PathwaySection.new(pathway_section_params)
      if @pathway_section.save
        redirect_to pathway_sections_url, notice: 'Pathway section was successfully created.'
      else
        render :new
      end
    end

    def update
      if @pathway_section.update(pathway_section_params)
        redirect_to pathway_sections_url, notice: 'Pathway section was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @pathway_section.destroy
      redirect_to pathway_sections_url, notice: 'Pathway section was successfully destroyed.'
    end

  private


    def set_pathway_section
      @pathway_section = PathwaySection.find(params[:id])
    end

    def pathway_section_params
      params.require(:pathway_section).permit(:name, :position, :pathway_rows_count, :pathway_jigsaw_pieces_count, :display)
    end
  end
end

app/controllers/optimadmin/testimonials_controller.rb
module Optimadmin
  class TestimonialsController < Optimadmin::ApplicationController
    before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

    def index
      @testimonials = Optimadmin::BaseCollectionPresenter.new(collection: Testimonial.service_filter(params[:service_id]).where('author ILIKE ?', "#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15),
                                                              view_template: view_context, presenter: Optimadmin::TestimonialPresenter)
    end

    def show
    end

    def new
      @testimonial = Testimonial.new
    end

    def edit
    end

    def create
      @testimonial = Testimonial.new(testimonial_params)
      if @testimonial.save
        redirect_to testimonials_url, notice: 'Testimonial was successfully created.'
      else
        render :new
      end
    end

    def update
      if @testimonial.update(testimonial_params)
        redirect_to testimonials_url, notice: 'Testimonial was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @testimonial.destroy
      redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.'
    end

  private


    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    def testimonial_params
      params.require(:testimonial).permit(:name, :author, :content, :display, :service_home, service_ids: [])
    end
  end
end

app/helpers/optimadmin/presenter_helper.rb
module Optimadmin
  module PresenterHelper
    def nested_admin_menu_items(menu_items:, depth: 1, menu_name:)
      menu_items.map do |menu_item, sub_menu_items|
        render partial: "optimadmin/menu_items/menu_item",
               locals: { menu_item_presenter: Optimadmin::MenuItemPresenter.new(object: menu_item, view_template: self, menu_name: menu_name),
                         sub_menu_items: sub_menu_items, depth: depth, menu_name: menu_name }
      end.join.html_safe
    end
  end
end

app/views/optimadmin/testimonials/_form.html.erb
<%= form_for(testimonial) do |f| %>
  <% if testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
        <% testimonial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="tabs prevent-flash">
    <ul class="tab-list">
      <li><a href="#tabs-1">Content</a></li>
      <li><a href="#tabs-2">Settings</a></li>
      <li>
        <%= link_to '#', class: 'destroy-tabs right', data: { class: 'tabs' } do %>
          <%= octicon('chevron-down') %>
        <% end %>
      </li>
    </ul>

    <%= field_set_tag nil, id: 'tabs-1' do %>
      <div class="field">
        <%= f.label :author %><br>
        <%= f.text_field :author %>
      </div>

      <div class="field">
        <%= f.label :content %><br>
        <%= f.text_area :content, class: 'tinymce' %>
      </div>
    <% end %>

    <%= field_set_tag nil, id: 'tabs-2' do %>
      <%= field_set_tag "Services" do %>
        <div class="field">
          <%= f.collection_check_boxes(:service_ids, Service.order(name: :asc), :id, :name) do |b| %>
            <%= b.check_box %>
            <%= b.label %><br/>
          <% end %>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :service_home %><br/>
        <%= f.check_box :service_home %>
      </div>

      <div class="field">
        <%= f.label :display %><br>
        <%= f.check_box :display %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/optimadmin/testimonials/_testimonial.html.erb
<div class="row collapse module-list-index <%= cycle('odd', 'even') %>" data-equalizer="module-list" id="item_<%= testimonial_presenter.id %>">
  <div class="large-9 small-8 columns" data-equalizer-watch="module-list">
    <%= testimonial_presenter.toggle_title %>
    <%= testimonial_presenter.services %>
  </div>

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= testimonial_presenter.toggle_link %>
  </div>

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= testimonial_presenter.edit_link %>
  </div>

  <div class="large-1 hide-for-medium-down columns last" data-equalizer-watch="module-list">
    <%= testimonial_presenter.delete_link %>
  </div>

  <div class="row module-list-detail hide" id="index-list-<%= testimonial_presenter.id %>">
    <div class="small-12 columns module-list-summary last">
      <%= testimonial_presenter.optimadmin_summary %>
    </div>
  </div>
</div>

app/views/optimadmin/testimonials/edit.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Edit Testimonal' %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: testimonials_path, title: 'Testimonal' %>

  <%= render 'form', testimonial: @testimonial %>
</div>

app/views/optimadmin/testimonials/index.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Manage Testimonals' %>

<div class="main-content">
  <div class="row module-header collapse">
    <%= render 'optimadmin/shared/module/index/new_item', title: 'Testimonal', object: Testimonial, path: new_testimonial_path %>
    <%= render 'optimadmin/shared/search_form' %>
    <%= render 'optimadmin/shared/module/index/pagination' %>
    <%= render 'optimadmin/shared/service_filter' %>
    <!--
      <%= render 'optimadmin/shared/module/index/order', options: [['Username', 'username']] %>
    -->
    <%= render 'optimadmin/shared/module/index/recycle_bin', items: @testimonials.size, path: root_url %>
  </div>

  <div class="row collapse module-list-index header">

    <%= list_item 'large-9 small-8' do 'Name' end %>

    <%= list_item { 'Display' } %>
    <%= list_item { 'Edit' } %>

    <%= list_item 'large-1 hide-for-medium-down text-center last' do 'Delete' end %>
  </div>

  <%= render partial: 'testimonial', collection: @testimonials, as: :testimonial_presenter %>
  <%= paginate @testimonials %>
</div>

app/views/optimadmin/testimonials/new.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'New Testimonal' %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: testimonials_path, title: 'Testimonal' %>

  <%= render 'form', testimonial: @testimonial %>
</div>