config/routes.rb
Rails.application.routes.draw do

  resources :pages, only: :show
  resources :contacts, only: [:new, :create]
  resources :articles, only: [:index, :show]
  resources :services, only: [:index, :show]
  resources :testimonials, only: [:index]
  resources :frequently_asked_questions, path: "frequently-asked-questions", only: [:index]

  root to: "application#index"
  mount Optimadmin::Engine => "/admin"
end
Optimadmin::Engine.routes.draw do

  resources :pathway_sections, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
    resources :pathway_jigsaw_pieces, except: [:show] do
      collection do
        post 'order'
      end
      member do
        get 'toggle'
      end
    end
    resources :pathway_rows, except: [:show] do
      collection do
        post 'order'
      end
      member do
        get 'toggle'
      end
    end
  end
  resources :locations, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :contact_details, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :frequently_asked_questions, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :testimonials, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :banners, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :services, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :pages, except: :show do
    collection do
      post 'order'
    end
    member do
      get 'edit_images'
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :articles, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
end

app/views/optimadmin/shared/sidebar/_module_links.html.erb
<div class="content-categories-sidebar">
  <div class="row collapse">
    <div class="small-8 show-for-medium-down columns">
      <%= link_to octicon('book') + 'Manage Content',
          '#',
          class: 'content-categories-toggle toggle-class',
          data: {
            class: 'content-categories-toggle-visiblity',
            container: '.content-categories, .content-categories-toggle',
            return: 'true'
          } %>
    </div>
    <div class="small-4 show-for-medium-down columns">
      <%= link_to logout_path, class: 'logout-link' do %>
        <%= octicon('sign-in') %> Logout
      <% end %>
    </div>
  </div>

  <div class="row collapse">
    <div class="large-12 small-8 left content-categories columns">
      <div class="content-category-type">
        Manage Your Content
      </div>

      <ul class="content-category-list">
        <% if can? :manage, Optimadmin::MenuItem %>
          <li><%= link_to 'Site Navigation', menu_items_path %></li>
        <% end %>
        <% if can? :manage, Page %>
          <li><%= link_to 'Pages', pages_path %></li>
        <% end %>
        <% if can? :manage, Service %>
          <li><%= link_to 'Services', services_path %></li>
        <% end %>
        <% if can? :manage, Article %>
          <li><%= link_to 'Articles', articles_path %></li>
        <% end %>
        <% if can? :manage, Testimonial %>
          <li><%= link_to 'Testimonials', testimonials_path %></li>
        <% end %>
        <% if can? :manage, FrequentlyAskedQuestion %>
          <li><%= link_to 'Frequently Asked Questions', frequently_asked_questions_path %></li>
        <% end %>
        <% if can? :manage, ContactDetail %>
          <li><%= link_to 'Contact Details', contact_details_path %></li>
        <% end %>
        <% if can? :manage, PathwaySection %>
          <li><%= link_to 'Pathway Sections', pathway_sections_path %></li>
        <% end %>
      </ul>

      <div class="content-category-type">
        Website Visuals
      </div>

      <ul class="content-category-list">
        <% if can? :manage, Banner %>
          <li><%= link_to 'Banners', banners_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>