config/routes.rb
Rails.application.routes.draw do

  resources :pages, only: :show
  resources :contacts, only: [:new, :create]
  resources :articles, only: [:index, :show]
  resources :services, only: [:index, :show]
  resources :testimonials, only: [:index]
  resources :frequently_asked_questions, path: "frequently-asked-questions", only: [:index]

  root to: "application#index"
  mount Optimadmin::Engine => "/admin"
end
Optimadmin::Engine.routes.draw do

  resources :pathway_sections, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
    resources :pathway_jigsaw_pieces, except: [:show] do
      collection do
        post 'order'
      end
      member do
        get 'toggle'
      end
    end
    resources :pathway_rows, except: [:show] do
      collection do
        post 'order'
      end
      member do
        get 'toggle'
      end
    end
  end
  resources :locations, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :contact_details, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :frequently_asked_questions, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :testimonials, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
    end
  end
  resources :banners, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :services, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :pages, except: :show do
    collection do
      post 'order'
    end
    member do
      get 'edit_images'
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
  resources :articles, except: [:show] do
    collection do
      post 'order'
    end
    member do
      get 'toggle'
      get 'edit_images'
      post 'update_image_default'
      post 'update_image_fill'
      post 'update_image_fit'
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]

  mount_uploader :image, ArticleUploader

  scope :published, -> { where("display = ? and date <= ?", true, Date.today) }

  validates :title, :content, :date, presence: true
  validates :suggested_url, allow_blank: true, uniqueness: { message: 'is not unique, leave this blank to generate automatically' }

  def slug_candidates
    [
      :suggested_url,
      :title,
      [:suggested_url, :title]
    ]
  end

  def should_generate_new_friendly_id?
    suggested_url_changed? || title_changed?
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]

  def index
    @presented_articles = BaseCollectionPresenter.new(collection: Article.published.order(date: :desc).page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: ArticlePresenter)
  end

  def show
    redirect_to @presented_article, status: :moved_permanently if article_path(@article) != request.path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.published.friendly.find(params[:id])
    @presented_article = ArticlePresenter.new(object: @article, view_template: view_context)
  end

end

app/controllers/optimadmin/articles_controller.rb
module Optimadmin
  class ArticlesController < Optimadmin::ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    edit_images_for Article, [[:image, { index: ['fill', 223, 223], show: ['fill', 215, 315], homepage: ['fill', '100, 100'] }]]

    def index
      @articles = Optimadmin::BaseCollectionPresenter.new(collection: Article.where('title ILIKE ?', "#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::ArticlePresenter)
    end

    def show
    end

    def new
      @article = Article.new
    end

    def edit
    end

    def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to articles_url, notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    def update
      if @article.update(article_params)
        redirect_to articles_url, notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @article.destroy
      redirect_to articles_url, notice: 'Article was successfully destroyed.'
    end

  private


    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :summary, :content, :image, :image_cache, :remote_image_url, :date, :display, :suggested_url)
    end
  end
end

app/controllers/optimadmin/banners_controller.rb
module Optimadmin
  class BannersController < Optimadmin::ApplicationController
    before_action :set_banner, only: [:show, :edit, :update, :destroy]

    edit_images_for Banner, [[:image, { homepage: ['fit', 560, 276] }]]

    def index
      @banners = Optimadmin::BaseCollectionPresenter.new(collection: Banner.order(position: :asc), view_template: view_context, presenter: Optimadmin::BannerPresenter)
    end

    def show
    end

    def new
      @banner = Banner.new
    end

    def edit
    end

    def create
      @banner = Banner.new(banner_params)
      if @banner.save
        redirect_to banners_url, notice: 'Banner was successfully created.'
      else
        render :new
      end
    end

    def update
      if @banner.update(banner_params)
        redirect_to banners_url, notice: 'Banner was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @banner.destroy
      redirect_to banners_url, notice: 'Banner was successfully destroyed.'
    end

  private


    def set_banner
      @banner = Banner.find(params[:id])
    end

    def banner_params
      params.require(:banner).permit(:name, :image, :image_cache, :remote_image_url, :content, :position, :display, :link)
    end
  end
end

app/controllers/optimadmin/contact_details_controller.rb
module Optimadmin
  class ContactDetailsController < Optimadmin::ApplicationController
    before_action :set_contact_detail, only: [:show, :edit, :update, :destroy]

    def index
      @contact_details = Optimadmin::BaseCollectionPresenter.new(collection: ContactDetail.service_filter(params[:service_id]).where('name ILIKE ?', "#{params[:search]}%").order(:service_id).page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::ContactDetailPresenter)
    end

    def show
    end

    def new
      @contact_detail = ContactDetail.new
    end

    def edit
    end

    def create
      @contact_detail = ContactDetail.new(contact_detail_params)
      if @contact_detail.save
        redirect_to contact_details_url, notice: 'Contact detail was successfully created.'
      else
        render :new
      end
    end

    def update
      if @contact_detail.update(contact_detail_params)
        redirect_to contact_details_url, notice: 'Contact detail was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @contact_detail.destroy
      redirect_to contact_details_url, notice: 'Contact detail was successfully destroyed.'
    end

  private


    def set_contact_detail
      @contact_detail = ContactDetail.find(params[:id])
    end

    def contact_detail_params
      params.require(:contact_detail).permit(:service_id, :name, :address, :postcode, :phone_number, :email, :opening_hours)
    end
  end
end

app/controllers/optimadmin/frequently_asked_questions_controller.rb
module Optimadmin
  class FrequentlyAskedQuestionsController < Optimadmin::ApplicationController
    before_action :set_frequently_asked_question, only: [:show, :edit, :update, :destroy]

    def index
      @frequently_asked_questions = Optimadmin::BaseCollectionPresenter.new(collection: FrequentlyAskedQuestion.service_filter(params[:service_id]).where('question ILIKE ?', "#{params[:search]}%").page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::FrequentlyAskedQuestionPresenter)
    end

    def show
    end

    def new
      @frequently_asked_question = FrequentlyAskedQuestion.new
    end

    def edit
    end

    def create
      @frequently_asked_question = FrequentlyAskedQuestion.new(frequently_asked_question_params)
      if @frequently_asked_question.save
        redirect_to frequently_asked_questions_url, notice: 'Frequently asked question was successfully created.'
      else
        render :new
      end
    end

    def update
      if @frequently_asked_question.update(frequently_asked_question_params)
        redirect_to frequently_asked_questions_url, notice: 'Frequently asked question was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @frequently_asked_question.destroy
      redirect_to frequently_asked_questions_url, notice: 'Frequently asked question was successfully destroyed.'
    end

  private


    def set_frequently_asked_question
      @frequently_asked_question = FrequentlyAskedQuestion.find(params[:id])
    end

    def frequently_asked_question_params
      params.require(:frequently_asked_question).permit(:question, :answer, :display, :service_home, service_ids: [])
    end
  end
end

app/controllers/optimadmin/pages_controller.rb
module Optimadmin
  class PagesController < Optimadmin::ApplicationController
    before_action :set_page, only: [:show, :edit, :update, :destroy]

    edit_images_for Page, [[:image, { show: ['fit', 756, 200] }]]

    def index
      @pages = Optimadmin::BaseCollectionPresenter.new(collection: Page.service_filter(params[:service_id]).where('title ILIKE ?', "#{params[:search]}%").order(:service_id).page(params[:page]).per(params[:per_page] || 15), view_template: view_context, presenter: Optimadmin::PagePresenter)
    end

    def show
    end

    def new
      @page = Page.new
    end

    def edit
    end

    def create
      @page = Page.new(page_params)
      if @page.save
        redirect_to pages_url, notice: 'Page was successfully created.'
      else
        render :new
      end
    end

    def update
      if @page.update(page_params)
        redirect_to pages_url, notice: 'Page was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @page.destroy
      redirect_to pages_url, notice: 'Page was successfully destroyed.'
    end

  private


    def set_page
      @page = Page.friendly.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:title, :suggested_url, :image, :image_cache, :remove_image, :remote_image_url,
                                   :display, :content, :style, :layout, :service_id)
    end
  end
end

app/controllers/optimadmin/pathway_jigsaw_pieces_controller.rb
module Optimadmin
  class PathwayJigsawPiecesController < Optimadmin::ApplicationController

    before_action :set_pathway_section
    before_action :set_pathway_jigsaw_piece, only: [:show, :edit, :update, :destroy]

    def index
      @pathway_jigsaw_pieces = Optimadmin::BaseCollectionPresenter.new(collection: @pathway_section.pathway_jigsaw_pieces.ordered,
                                       view_template: view_context, presenter: Optimadmin::PathwayJigsawPiecePresenter)
    end

    def show
    end

    def new
      @pathway_jigsaw_piece = @pathway_section.pathway_jigsaw_pieces.new
    end

    def edit
    end

    def create
      @pathway_jigsaw_piece = @pathway_section.pathway_jigsaw_pieces.new(pathway_jigsaw_piece_params)
      if @pathway_jigsaw_piece.save
        redirect_to pathway_section_pathway_jigsaw_pieces_url(@pathway_section), notice: 'Pathway jigsaw piece was successfully created.'
      else
        render :new
      end
    end

    def update
      if @pathway_jigsaw_piece.update(pathway_jigsaw_piece_params)
        redirect_to pathway_section_pathway_jigsaw_pieces_url(@pathway_section), notice: 'Pathway jigsaw piece was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @pathway_jigsaw_piece.destroy
      redirect_to pathway_section_pathway_jigsaw_pieces_url(@pathway_section), notice: 'Pathway jigsaw piece was successfully destroyed.'
    end

  private

    def set_pathway_section
      @pathway_section = PathwaySection.find(params[:pathway_section_id])
    end

    def set_pathway_jigsaw_piece
      @pathway_jigsaw_piece = @pathway_section.pathway_jigsaw_pieces.find(params[:id])
    end

    def pathway_jigsaw_piece_params
      params.require(:pathway_jigsaw_piece).permit(:pathway_section_id, :name, :position, :colour, :display)
    end
  end
end

app/controllers/optimadmin/pathway_rows_controller.rb
module Optimadmin
  class PathwayRowsController < Optimadmin::ApplicationController

    before_action :set_pathway_section
    before_action :set_pathway_row, only: [:show, :edit, :update, :destroy]

    def index
      @pathway_rows = Optimadmin::BaseCollectionPresenter.new(collection: @pathway_section.pathway_rows.ordered,
                                                view_template: view_context, presenter: Optimadmin::PathwayRowPresenter)
    end

    def show
    end

    def new
      @pathway_row = @pathway_section.pathway_rows.new
    end

    def edit
    end

    def create
      @pathway_row = @pathway_section.pathway_rows.new(pathway_row_params)
      if @pathway_row.save
        redirect_to pathway_section_pathway_rows_url(@pathway_section), notice: 'Pathway row was successfully created.'
      else
        render :new
      end
    end

    def update
      if @pathway_row.update(pathway_row_params)
        redirect_to pathway_section_pathway_rows_url(@pathway_section), notice: 'Pathway row was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @pathway_row.destroy
      redirect_to pathway_section_pathway_rows_url(@pathway_section), notice: 'Pathway row was successfully destroyed.'
    end

  private

    def set_pathway_section
      @pathway_section = PathwaySection.find(params[:pathway_section_id])
    end

    def set_pathway_row
      @pathway_row = @pathway_section.pathway_rows.find(params[:id])
    end

    def pathway_row_params
      params.require(:pathway_row).permit(:pathway_section_id, :name, :content, :colour, :display)
    end
  end
end

app/controllers/optimadmin/pathway_sections_controller.rb
module Optimadmin
  class PathwaySectionsController < Optimadmin::ApplicationController
    before_action :set_pathway_section, only: [:show, :edit, :update, :destroy]

    def index
      @pathway_sections = Optimadmin::BaseCollectionPresenter.new(collection: PathwaySection.ordered,
                                  view_template: view_context, presenter: Optimadmin::PathwaySectionPresenter)
    end

    def show
    end

    def new
      @pathway_section = PathwaySection.new
    end

    def edit
    end

    def create
      @pathway_section = PathwaySection.new(pathway_section_params)
      if @pathway_section.save
        redirect_to pathway_sections_url, notice: 'Pathway section was successfully created.'
      else
        render :new
      end
    end

    def update
      if @pathway_section.update(pathway_section_params)
        redirect_to pathway_sections_url, notice: 'Pathway section was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @pathway_section.destroy
      redirect_to pathway_sections_url, notice: 'Pathway section was successfully destroyed.'
    end

  private


    def set_pathway_section
      @pathway_section = PathwaySection.find(params[:id])
    end

    def pathway_section_params
      params.require(:pathway_section).permit(:name, :position, :pathway_rows_count, :pathway_jigsaw_pieces_count, :display)
    end
  end
end

app/helpers/optimadmin/presenter_helper.rb
module Optimadmin
  module PresenterHelper
    def nested_admin_menu_items(menu_items:, depth: 1, menu_name:)
      menu_items.map do |menu_item, sub_menu_items|
        render partial: "optimadmin/menu_items/menu_item",
               locals: { menu_item_presenter: Optimadmin::MenuItemPresenter.new(object: menu_item, view_template: self, menu_name: menu_name),
                         sub_menu_items: sub_menu_items, depth: depth, menu_name: menu_name }
      end.join.html_safe
    end
  end
end

app/views/optimadmin/articles/_article.html.erb
<div class="row collapse module-list-index <%= cycle('odd', 'even') %>" data-equalizer="module-list" id="item_<%= article_presenter.id %>">

  <div class="large-6 small-12 columns" data-equalizer-watch="module-list">
    <%= article_presenter.toggle_title %>
  </div>


    <div class="large-2 hide-for-medium-down columns" data-equalizer-watch="module-list">
      <%= article_presenter.edit_image(:image)%>
    </div>


  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= article_presenter.toggle_link %>
  </div>

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= article_presenter.show_link %>
  </div>

  <div class="large-1 small-4 columns" data-equalizer-watch="module-list">
    <%= article_presenter.edit_link %>
  </div>

  <div class="large-1 hide-for-medium-down columns last" data-equalizer-watch="module-list">
    <%= article_presenter.delete_link %>
  </div>

  <div class="row module-list-detail hide" id="index-list-<%= article_presenter.id %>">
    <div class="small-12 columns module-list-summary last">
      <%= article_presenter.optimadmin_summary %>
    </div>
  </div>
</div>

app/views/optimadmin/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="tabs prevent-flash">
    <ul class="tab-list">
      <li><a href="#tabs-1">Content</a></li>
      <li><a href="#tabs-2">Media</a></li>
      <li><a href="#tabs-3">Settings</a></li>
      <li>
        <%= link_to '#', class: 'destroy-tabs right', data: { class: 'tabs' } do %>
          <%= octicon('chevron-down') %>
        <% end %>
      </li>
    </ul>

    <%= field_set_tag nil, id: 'tabs-1' do %>
      <div class="field">
        <%= f.label :summary %><br>
        <%= f.text_area :summary %>
      </div>

      <div class="field">
        <%= f.label :content %><br>
        <%= f.text_area :content, class: 'tinymce' %>
      </div>
    <% end %>

    <%= field_set_tag nil, id: 'tabs-2' do %>
      <div class="field">
        <%= f.label :image %><br>
        <%= f.image_field :image %>
      </div>
    <% end %>

    <%= field_set_tag nil, id: 'tabs-3' do %>
      <div class="field">
        <%= f.label :date %><br>
        <%= f.date_select :date %>
      </div>

      <div class="field">
        <%= f.label :suggested_url %><br>
        <%= f.text_field :suggested_url %>
      </div>

      <div class="field">
        <%= f.label :display %><br>
        <%= f.check_box :display %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/optimadmin/articles/edit.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Edit Article' %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: articles_path, title: 'Article' %>

  <%= render 'form', article: @article %>
</div>

app/views/optimadmin/articles/index.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Manage Articles' %>

<div class="main-content">
  <div class="row module-header collapse">
    <%= render 'optimadmin/shared/module/index/new_item', title: 'Article', object: Article, path: new_article_path %>
    <%= render 'optimadmin/shared/search_form' %>
    <%= render 'optimadmin/shared/module/index/pagination' %>
    <!--
      <%= render 'optimadmin/shared/module/index/order', options: [['Username', 'username']] %>
    -->
    <%= render 'optimadmin/shared/module/index/recycle_bin', items: @articles.size, path: root_url %>
  </div>

  <div class="row collapse module-list-index header">
    <%= list_item 'large-6 small-12' do 'Title' end %>

    <%= list_item 'large-2 hide-for-medium-down' do 'Image' end %>

    <%= list_item { 'Display' } %>
    <%= list_item { 'View' } %>
    <%= list_item { 'Edit' } %>

    <%= list_item 'large-1 hide-for-medium-down text-center last' do 'Delete' end %>
  </div>

  <%= render partial: 'article', collection: @articles, as: :article_presenter %>
  <%= paginate @articles %>
</div>

app/views/optimadmin/articles/new.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'New Article' %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: articles_path, title: 'Article' %>

  <%= render 'form', article: @article %>
</div>